
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8081:8081 # Usa la variable de entorno PORT para el puerto
    environment:
      - MONGO_URI=mongodb://${userName}:${password}@callcoder.1tibfdt.mongodb.net/?retryWrites=true&w=majority # Usa las variables de entorno del archivo .env
    depends_on:
      - mongo
    volumes:
      - .:/app # Sincroniza los archivos locales con el contenedor
      - /app/node_modules # Evita conflictos con node_modules

  mongo:
    image: mongo:6.0
    container_name: callcoder # Nombre del contenedor de MongoDB
    ports:
      - "27017:27017" # Puerto predeterminado de MongoDB
    volumes:
      - mongo-data:/data/db # Persistencia de datos

volumes:
  mongo-data: